server:
  port: 8001
spring:
#  application:
#    name: fans-admin
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.140.117.214:3306/mango?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      # connect
      max-active: 100
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      # test
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # filter
      filters: stat,wall,log4j,config
      stat-view-servlet:
        enabled: true
